name: 'build-src and doc'
description: 'Build src of libcimpp'
inputs:
  use_cim_version:  # id of input    
    required: true
    default: 'IEC61970_16v29a'
  input_dir: 
    required: true
    default: '~'
  build_type: 
    required: true
    default: 'src'
runs: 
  using: "composite"
  steps:
      - name: Install Doxygen
        run: sudo apt-get install doxygen 
        shell: bash 
      - run: cd ${{inputs.input_dir}}
        shell: bash
      - run: cmake -E make_directory ${{inputs.input_dir}}/build/${{inputs.use_cim_version}}
        shell: bash
      - run: cd build/${{inputs.use_cim_version }} #cd ${{inputs.input_dir}}/build/${{inputs.use_cim_version }}
        shell: bash
      - run: cmake ${{inputs.input_dir}} -DUSE_CIM_VERSION=${{inputs.use_cim_version }}
        shell: bash

      - name: build-doc
        run: make doc
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: doc
          path: ${{runner.workspace}}/libcimpp/build/IEC61970_16v29a/doc/html
          retention-days: 90

      
      - name: build-src 
        run: make -j8
        shell: bash





