name: test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: libcimpp-dev


jobs:


  .build-src: &build-src
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{CIM_VERSION}}
      
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{CIM_VERSION}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{CIM_VERSION}} 
          cmake ../.. -DUSE_CIM_VERSION=${{CIM_VERSION}} 
          make -j8
    
    
  build-src-IEC61970_16v29a:
    <<: *build-src
    env:
      CIM_VERSION: IEC61970_16v29a
